### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by salody** [NervJS/taro-plugin-platform-alipay-dd#1]
这个插件只支持Taro 3吗？是否支持taro2？
在taro2.2.6中使用报错
UnhandledPromiseRejectionWarning: TypeError: this.ctx.modifyMiniConfigs is not a function

**Comment by honlyHuang** [comment]
> 这个插件只支持Taro 3吗？是否支持taro2？
> 在taro2.2.6中使用报错
> UnhandledPromiseRejectionWarning: TypeError: this.ctx.modifyMiniConfigs is not a function

3.1 以上才支持的咯
