### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by maimai123** [NervJS/taro-plugin-platform-alipay-dd#10]
![image](https://user-images.githubusercontent.com/15125340/130387162-53c69c35-17be-47eb-9f21-46448f7b4f3a.png)

![image](https://user-images.githubusercontent.com/15125340/130387175-af9621ab-0a16-4df9-aad9-436a480274b1.png)

**Comment by Chen-jj** [comment]
## 版本要求

### Taro 3.3.8+

请使用本插件的 `~0.1.0` 版本

### Taro 3.1 & 3.2

请使用本插件的 `~0.0.5` 版本
