### ISSUE TITLE
钉钉小程序不支持 getPhoneNumber 获取手机号

### ISSUE THREAD

**Issue by SkyeSun** [NervJS/taro-plugin-platform-alipay-dd#11]
> Taro: 3.2.13
> @tarojs/plugin-platform-alipay-dd: 0.0.5

![image](https://user-images.githubusercontent.com/16323946/132666145-1e996878-fd7e-4408-b7a0-e9ceea846802.png)

```html
<button 
    className='login-btn' 
    openType='getAuthorize' 
    scope='phoneNumber' 
    onGetAuthorize={onGetAuthorize} 
    onError={onAuthError}
>
    点击登录
</button>
```

```javascript
  const onGetAuthorize = () => {
    // @ts-ignore
    Taro.getPhoneNumber({
      success: (res) => {
        console.log('getPhoneNumber_success!');
        console.log('----------- res: ', res)
      },
      fail: (res) => {
        console.log(res);
        console.log('getPhoneNumber_fail');
      },
    });
  }
```

**Comment by Chen-jj** [comment]
直接用 `dd. getPhoneNumber` 可以不

**Comment by SkyeSun** [comment]
> 直接用 `dd. getPhoneNumber` 可以不

试过了，也是不可以，会直接报错：
![image](https://user-images.githubusercontent.com/16323946/132787531-9e902a0b-f2d4-4437-8ffe-baf929272e68.png)
还是需要先引入什么包之类的吗？？

**Comment by Chen-jj** [comment]
首先看看钉钉的文档有没有这个 API 咯，Taro 只是透传调用小程序的 API 而已：

```js
Taro.getPhoneNumber() -> dd.getPhoneNumber()
```

**Comment by SkyeSun** [comment]
确认了，钉钉小程序没有 getPhoneNumber 这个 api，获取手机号需要调用钉钉提供的公共接口，走另外的免登逻辑：https://developers.dingtalk.com/document/app/enterprise-internal-application-logon-free

感谢回复！[抱拳][抱拳][抱拳]

**Comment by DongDaYo** [comment]
怎么引入dd这个API对象呀

**Comment by SkyeSun** [comment]
> 怎么引入dd这个API对象呀

代码里直接使用 dd.xxx() 调用即可，在钉钉运行环境下会自动识别出这个对象，如果有 ts 报错用 //@ts-ignore 忽略
