### ISSUE TITLE
Taro框架Vue版本编译钉钉小程序

### ISSUE THREAD

**Issue by xmong123** [NervJS/taro-plugin-platform-alipay-dd#18]
Taro框架Vue版本编译钉钉小程序无报错，页面不展示
<img width="960" alt="未命名1654597905" src="https://user-images.githubusercontent.com/5009767/172516278-38932358-dbfc-4309-be7f-263fae98934e.png">
无法排查问题

**Comment by Chen-jj** [comment]
没有复现，可以升级到最新版本后再试试
