### ISSUE TITLE
Taro 钉钉插件编译不渲染部分组件

### ISSUE THREAD

**Issue by winfcloud** [NervJS/taro-plugin-platform-alipay-dd#20]
Taro Cli 3.5.5 React版本 编译钉钉小程序无报错无警告，不编译部分组件

使用技术:
Taro Cli 3.5.5 
React 默认模板，
使用Sass
不使用ts
Webpack 5
安装钉钉插件

问题:
引入的Button组件无警告，不编译

![Snipaste_2022-09-16_15-41-18](https://user-images.githubusercontent.com/15316139/190584638-a365c150-e27e-400d-a4fe-9b825fd0eb9d.png)
![Snipaste_2022-09-16_15-35-21](https://user-images.githubusercontent.com/15316139/190584631-5d8f4365-2420-45d4-a786-36c61511b5c8.png)

**Comment by zhaihongbin** [comment]
😭升级taro至3.5.x发现很多组件都不编译了，比如input、webview等

**Comment by xiayifeng** [comment]
还有人维护吗

**Comment by Chen-jj** [comment]
https://github.com/NervJS/taro/issues/13478
