### ISSUE TITLE
项目引入钉钉插件后打包 build:xx 报错，环境 taro3.5.6+vue3+typescript+webpack5+sass

### ISSUE THREAD

**Issue by owmjess** [NervJS/taro-plugin-platform-alipay-dd#23]
使用npx @tarojs/cli init myApp，新建项目
**环境：taro3.5.6+vue3+typescript+webpack5+sass**

``
plugins: ['@tarojs/plugin-platform-alipay-dd'],
``
安装 @taro-plugin-platform-alipay-dd，并按官方配置操作后，所有 build:xx 原来正常打包，都会报错无法完成 build。报错如下，如果有页面有其他组件或第三方插件会有其他错误信息。

但是 dev:xx 反而可以正常完成。

``` sh
✖ Errors: 

Error: Cannot get final name for export 'effectScope' of ./node_modules/.pnpm/vue-demi@0.14.0_vue@3.2.24/node_modules/vue-demi/lib/index.mjs

 ELIFECYCLE  Command failed with exit code 1.

```

如果去除@tarojs/plugin-platform-alipay-dd相关配置，所有build:xx可以正常操作。

**Comment by bigmeow** [comment]
更新到 `0.3.0` 版本可以解决这个问题
