### ISSUE TITLE
升级 0.2.0 后报错 Error: Cannot get final name for export 'xx' of  xxx

### ISSUE THREAD

**Issue by bigmeow** [NervJS/taro-plugin-platform-alipay-dd#24]
- 创建一个新 `taro` 项目, 安装使用 `"@tarojs/plugin-platform-alipay-dd": "0.2.0"`,
- 代码中随便导入任何一个安装的npm包，执行编译 dd 小程序，会报 `Cannot get final name for export 'xx' of  xxx` 形式的错误。插件版本降级到 0.1.3 后编译才能通过。
- 调试后发现还是 `optimization. providedExports ` 修改导致的， 去掉插件中`optimization. providedExports`相关改动编译即可通过

复现代码：
[bug.zip](https://github.com/NervJS/taro-plugin-platform-alipay-dd/files/11912468/bug.zip)

**Comment by journey-xt** [comment]
请问这个问题  何时修复
