### ISSUE TITLE
是否可以在插件内部对于webpack 中 output.globalObject 属性值 修改为 'dd'。

### ISSUE THREAD

**Issue by journey-xt** [NervJS/taro-plugin-platform-alipay-dd#26]
Alipay Mini Program Global Variable is  'my',而钉钉小程序为‘dd’

**Comment by Chen-jj** [comment]
看了下钉钉小程序中 my 和 dd 是等价的，应该没有关系吧

**Comment by Chen-jj** [comment]
了解~已改

> 我只是 出于对于 API使用条件下，对于 支付宝 API 使用 是针对 my 全局对象上，而钉钉小程序 是 dd 对象上。在此基础上对于某些业务需要，在打包过程中一些配置我们是挂载到对应的平台全局对象上的。对此提出的这次修改。当然这不是必选的。

**Comment by journey-xt** [comment]
非常感谢。此修改不知道是否会针对 其他开发者 有没有  影响。你们也请考虑一下。
