### ISSUE TITLE
编译后在钉钉开发工具打开报错

### ISSUE THREAD

**Issue by yxwwk** [NervJS/taro-plugin-platform-alipay-dd#5]
taro build --type dd --watch  编译成功后：
taro 版本  Taro v3.1.0-beta.5

**Error: ./custom-wrapper.axml
Module build failed :
Error: custom-wrapper.axml
Module build failed:
/base[object Object].axml not exists!**

没有加代码，Taro拉取的Demo
选的是TypeScript

**Comment by Chen-jj** [comment]
开发阿里系小程序先用 3.1.0-beta.4 咯，下一个小版本修复：https://github.com/NervJS/taro/issues/8628

**Comment by yxwwk** [comment]
好的谢啦

**Comment by Chen-jj** [comment]
已发 beta.6
