### ISSUE TITLE
Taro.navigateTo 在钉钉小程序里面报错？

### ISSUE THREAD

**Issue by yxwwk** [NervJS/taro-plugin-platform-alipay-dd#6]
Taro v3.1.0-beta.4
错误如下：
TypeError: _tarojs_taro__WEBPACK_IMPORTED_MODULE_2___default.a.navigateTo is not a function
    at TaroElement.onClick (index.js:34)
    at TaroElement.dispatchEvent (taro.js:2760)
    at Object.eventHandler [as eh] (taro.js:1054)

**Comment by Chen-jj** [comment]
复现不了，升级到最新版再试试

**Comment by yxwwk** [comment]
哈喽！昨天我升级了下taro 版本，v3.1.0-beta.6   发现： Taro.getSystemInfoSync 在钉钉里面无效了。 Taro.request({}) 在钉钉里面也报错了。 还有其它的一些报错，我就认为Taro的好多方法无效了。 我就退回到v3.1.0-beta.5，我手动改了插件的依赖可以在钉钉上跑。 我这边用的小程序开发工具版本是：版本1.15.7 (Changelog). 不知道是不是我这边有地方没有注意到    



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "chenjiajian"<notifications@github.com&gt;; 
发送时间: 2021年2月10日(星期三) 中午12:14
收件人: "NervJS/taro-plugin-platform-alipay-dd";
抄送: "Author";
主题: Re: [NervJS/taro-plugin-platform-alipay-dd] Taro.navigateTo 在钉钉小程序里面报错？ (#6)





 
Closed #6.
 
&mdash;

**Comment by Chen-jj** [comment]
@yxwwk beta6 对插件结构进行了大改，Taro 和插件都还要再发一个版本

**Comment by Chen-jj** [comment]
> @yxwwk beta6 对插件结构进行了大改，Taro 和插件都还要再发一个版本

可以试试最新的 Taro `v3.1.0-beta.7` 和 钉钉插件 `v0.0.3`
