### ISSUE TITLE
钉钉小程序配置了自定义导航栏无效？

### ISSUE THREAD

**Issue by yxwwk** [NervJS/taro-plugin-platform-alipay-dd#7]
Taro v3.1.0-beta.5
index.config.ts 配置如下：
export default {
  navigationBarTextStyle: 'white',
  backgroundColor: '#fff',
  navigationStyle: 'custom',
  disableScroll: false,
}
钉钉小程序要如何隐藏导航栏呀？

**Comment by Chen-jj** [comment]
@yxwwk 支付宝小程序都没有这个特性吧：https://opendocs.alipay.com/mini/framework/page-json
