### ISSUE TITLE
taro 3x中将插件clone下来本地引入，使用 api报错

### ISSUE THREAD

**Issue by asasugar** [NervJS/taro-plugin-platform-alipay-dd#8]
我本地引入的目的是想基于阿里系自定义开发插件。
首先git clone 插件，到插件目录yarn,然后yran build

然后在config/index.js的plugins选项中引入本地绝对路径'/Users/xj/github/taro-plugin-platform-alipay-dd'

在项目中使用Taro.showCallMenu()

![image](https://user-images.githubusercontent.com/27256120/108493591-73be6e00-72e1-11eb-8be2-534eeb960b71.png)

**Comment by Chen-jj** [comment]
复现不了，Taro 什么版本？

**Comment by xxj95719** [comment]
> 复现不了，Taro 什么版本？

3.0.27

**Comment by Chen-jj** [comment]
3.1才有这个功能

**Comment by xxj95719** [comment]
> 3.1才有这个功能

3.2.0-canary.8不支持吗

**Comment by xxj95719** [comment]
> > 3.1才有这个功能
> 
> 3.2.0-canary.8不支持吗

经过测试，next版本（3.1.0-beta.7）支持插件，canary版本不支持，关于插件两个版本的差异代码是在哪？

**Comment by Chen-jj** [comment]
3.2 支持了 RN，等 3.1 发正式版后，3.2 会 merge 3.1

**Comment by xxj95719** [comment]
> 3.2 支持了 RN，等 3.1 发正式版后，3.2 会 merge 3.1

一个新的问题，3.1版本config/index.js plugin用本地绝对路径，还是会去myApp下的node_modules中去查找
![image](https://user-images.githubusercontent.com/27256120/108589785-1850b680-739b-11eb-8d8a-ab3afabf1561.png)

**Comment by Chen-jj** [comment]
![image](https://user-images.githubusercontent.com/11807297/108617137-d5e8b180-744e-11eb-9aa2-c7d17eb6b783.png)

![image](https://user-images.githubusercontent.com/11807297/108617142-dc772900-744e-11eb-862c-c12f7ee40eea.png)

没有复现喔

**Comment by xxj95719** [comment]
> ![image](https://user-images.githubusercontent.com/11807297/108617137-d5e8b180-744e-11eb-9aa2-c7d17eb6b783.png)
> 
> ![image](https://user-images.githubusercontent.com/11807297/108617142-dc772900-744e-11eb-862c-c12f7ee40eea.png)
> 
> 没有复现喔

将taro项目的node_modules中已经下载的插件包删除，如果之前下载过，没有删除，使用本地路径还是会去node_modules中找
