### ISSUE TITLE
此包不兼容@tarojs/plugin-platform-alipay 3.3.1

### ISSUE THREAD

**Issue by leidenglai** [NervJS/taro-plugin-platform-alipay-dd#9]
因为dependencies 中：
    "@tarojs/plugin-platform-alipay": "^3.1.3"

导致会自动依赖plugin-platform-alipay最新的majar major 3.3.1， 但是plugin-platform-alipay 3.3.1没有导出noPromiseApis
所以：

./node_modules/@tarojs/plugin-platform-alipay-dd/dist/runtime.js 9:56-69
" '@tarojs/plugin-platform-alipay/dist/runtime-utils' does not contain an export named 'noPromiseApis'.

**Comment by Chen-jj** [comment]
`@tarojs/plugin-platform-alipay@0.1.0`可以兼容 Taro v3.3.8+ 版本了
